const relaxedActionCellClass = '!px-4'

export const apiKeyColumns = [
  { key: 'selection', label: '', width: '48px', minWidth: '48px', align: 'center' as const },
  {
    key: 'identity',
    label: '名称',
    sortable: true,
    sortKey: 'name',
    minWidth: '220px',
    flex: 0.9,
  },
  { key: 'prefix', label: '密钥前缀', minWidth: '180px', flex: 1 },
  {
    key: 'enabled',
    label: '状态',
    sortable: true,
    width: '112px',
    minWidth: '112px',
    align: 'center' as const,
  },
  { key: 'scope', label: '分组', width: '112px', minWidth: '112px' },
  {
    key: 'createdAtDisplay',
    label: '创建时间',
    sortable: true,
    sortKey: 'createdAt',
    width: '176px',
    minWidth: '176px',
    cellClass: 'font-mono text-[12px] font-emphasis tabular-nums text-(--cp-text-secondary)',
  },
  {
    key: 'lastUsedAt',
    label: '最后使用',
    sortable: true,
    sortKey: 'lastUsedAt',
    width: '176px',
    minWidth: '176px',
    emptyText: '',
    headerClass: '!pl-8',
    cellClass: '!pl-8 text-(--cp-text-secondary)',
  },
  {
    key: 'actions',
    label: '操作',
    width: '172px',
    minWidth: '172px',
    headerClass: relaxedActionCellClass,
    cellClass: relaxedActionCellClass,
  },
]
