import type {
  ThemeColorRoleRecipes,
  ThemeName,
} from '../types'

/** 明暗算法只描述 Palette 到 Map Token 的角色关系，不携带具体品牌颜色。 */
export const THEME_COLOR_ROLE_RECIPES = {
  light: {
    primary: {
      color: 'seed',
      hover: 5,
      active: 7,
      textHover: 5,
      text: 6,
      textActive: 7,
      backgroundMix: 0.09,
      backgroundHoverMix: 0.14,
      backgroundActiveMix: 0.18,
      borderMix: 0.46,
      borderHoverMix: 0.56,
    },
    semantic: {
      color: 6,
      hover: 5,
      active: 7,
      textHover: 5,
      text: 6,
      textActive: 7,
      backgroundMix: 0.08,
      backgroundHoverMix: 0.12,
      backgroundActiveMix: 0.18,
      borderMix: 0.4,
      borderHoverMix: 0.5,
      hoverContrast: 3,
      activeContrast: 3,
    },
    preset: {
      solid: 6,
      text: 7,
      textOnBackground: 7,
      backgroundMix: 0.08,
      backgroundStrongMix: 0.22,
      borderMix: 0.4,
    },
  },
  dark: {
    primary: {
      color: 'seed',
      hover: 8,
      active: 6,
      textHover: 8,
      text: 7,
      textActive: 6,
      backgroundMix: 0.17,
      backgroundHoverMix: 0.24,
      backgroundActiveMix: 0.3,
      borderMix: 0.52,
      borderHoverMix: 0.62,
    },
    semantic: {
      color: 6,
      hover: 8,
      active: 6,
      textHover: 8,
      text: 9,
      textActive: 10,
      backgroundMix: 0.18,
      backgroundHoverMix: 0.24,
      backgroundActiveMix: 0.3,
      borderMix: 0.46,
      borderHoverMix: 0.56,
      hoverContrast: 3,
      activeContrast: 3,
    },
    preset: {
      solid: 6,
      text: 8,
      textOnBackground: 8,
      backgroundMix: 0.18,
      backgroundStrongMix: 0.24,
      borderMix: 0.46,
      minimumTextLightness: 0.7,
    },
  },
} as const satisfies Record<ThemeName, ThemeColorRoleRecipes>
